included:
    - Sources
    - Tests
disabled_rules:
    - nesting
    - trailing_newline
    - force_cast
    - function_body_length
    - identifier_name
    - line_length
    - trailing_whitespace
    - type_name
    - type_body_length
    - todo
    - file_length
    - leading_whitespace
    - mark
    - function_parameter_count
    - cyclomatic_complexity
    - colon
    - fallthrough
    - empty_enum_arguments
    - unused_optional_binding
    - empty_parentheses_with_trailing_closure
    - closure_parameter_position
    - vertical_whitespace
    - trailing_comma
    - xctfail_message
    - class_delegate_protocol
    - redundant_optional_initialization
custom_rules:
  double_space:
    include: "*.swift"
    name: "Double space" 
    regex: "([a-z,A-Z] \\s+)" 
    message: "Double space between keywords" 
    match_kinds: keyword 
    severity: warning
