# .circleci/config.yml

# Specify the config version - version 2 is latest.
version: 2

# Define the jobs for the current project.
jobs:
  build-and-test:

    environment:
      - DESTINATION: "platform=iOS Simulator,name=iPhone XS"

    # Specify the Xcode version to use.
    macos:
      xcode: "10.2.0"

    # Define the steps required to build the project.
    steps:

      # Get the code from the VCS provider.
      - checkout
      - run:
          name: Build framework
          command: xcodebuild build -project InputBarAccessoryView.xcodeproj -scheme InputBarAccessoryView -destination "$DESTINATION" CODE_SIGNING_REQUIRED=NO | xcpretty -c
      - run:
          name: Report CodeCov
          command: bash <(curl -s https://codecov.io/bash) -t "849130fe-2cf2-4614-bc81-35c44cf9324c"
      - run: 
          name: Fetch CocoaPods Specs
          command: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run:
          name: Build and analyze Example
          command: xcodebuild build analyze -workspace InputBarAccessoryView.xcworkspace -scheme Example -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
