name: Swift

on:
  push:
    branches:
      - wired3

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Build
        run: swift build
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.2
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Build
        run: swift build